nato_dict = {'A': 'Alpha', 
             'B': 'Bravo',
             'C': 'Charlie',
             'D': 'Delta',
             'E': 'Echo',
             'F': 'Foxtrot',
             'G': 'Golf',
             'H': 'Hotel',
             'I': 'India',
             'J': 'Juliett',
             'K': 'Kilo',
             'L': 'Lima',
             'M': 'Mike',
             'N': 'November',
             'O': 'Oscar',
             'P': 'Papa',
             'Q': 'Quebec',
             'R': 'Romeo',
             'S': 'Sierra',
             'T': 'Tango',
             'U': 'Uniform',
             'V': 'Victor',
             'W': 'Whiskey',
             'X': 'X-ray',
             'Y': 'Yankee',
             'Z': 'Zulu'}

word = input('Input the word: ').upper()
print(*[nato_dict.get(i) for i in word])
